// SPDX-FileCopyrightText: 2026 Samer Ali
// SPDX-License-Identifier: GPL-3.0-only

#include "aieplugin/kernels/KernelRegistryService.hpp"

#include <utils/EnvironmentQtPolicy.hpp>
#include <utils/PathUtils.hpp>
#include <utils/filesystem/FileSystemUtils.hpp>
#include <utils/filesystem/JsonFileUtils.hpp>

#include <QtCore/QCoreApplication>
#include <QtCore/QDir>
#include <QtCore/QFile>
#include <QtCore/QFileInfo>
#include <QtCore/QJsonArray>
#include <QtCore/QJsonObject>
#include <QtCore/QLoggingCategory>

Q_LOGGING_CATEGORY(aiekernelregistrylog, "ironsmith.aie.kernelregistry")

namespace Aie::Internal {

namespace {

QString appDataSubDir(const QString& root, const QString& subPath)
{
    if (root.trimmed().isEmpty() || subPath.trimmed().isEmpty())
        return {};
    return Utils::PathUtils::normalizePath(QDir(root).filePath(subPath));
}

QString makeCopyFolderName(const QString& kernelId)
{
    QString cleaned = Utils::PathUtils::sanitizeFileName(kernelId.trimmed());
    cleaned.replace(' ', '_');
    if (cleaned.isEmpty())
        cleaned = QStringLiteral("kernel_copy");
    return cleaned;
}

QString makeKernelIdentifier(QString kernelId)
{
    kernelId = kernelId.trimmed();
    if (kernelId.isEmpty())
        return {};

    QString normalized;
    normalized.reserve(kernelId.size());
    for (const QChar ch : kernelId) {
        if (ch.isLetterOrNumber() || ch == u'_' || ch == u'-' || ch == u'.') {
            normalized.append(ch);
        } else if (ch.isSpace()) {
            normalized.append(u'_');
        } else {
            normalized.append(u'_');
        }
    }

    normalized = normalized.trimmed();
    while (normalized.startsWith('.'))
        normalized.remove(0, 1);
    while (normalized.endsWith('.'))
        normalized.chop(1);

    if (normalized.isEmpty())
        return {};

    return normalized;
}

QString defaultKernelName(const QString& kernelId)
{
    QString name = kernelId;
    name.replace('_', ' ');
    name.replace('-', ' ');
    return name.trimmed();
}

QString defaultKernelSignature(const QString& kernelId)
{
    QString functionName = makeKernelIdentifier(kernelId);
    if (functionName.isEmpty())
        functionName = QStringLiteral("kernel_entry");
    functionName.replace('.', '_');
    functionName.replace('-', '_');
    functionName.replace(' ', '_');
    return QStringLiteral("void %1();").arg(functionName);
}

QString normalizedSignature(QString signature, const QString& kernelId)
{
    signature = signature.trimmed();
    if (signature.isEmpty())
        signature = defaultKernelSignature(kernelId);

    if (!signature.endsWith(';'))
        signature.append(';');
    return signature;
}

QString definitionFromSignature(QString signature, const QString& kernelId)
{
    signature = normalizedSignature(std::move(signature), kernelId);
    if (signature.endsWith(';'))
        signature.chop(1);
    return signature.trimmed();
}

QString createSourceTemplate(const QString& signature, const QString& kernelId)
{
    const QString definition = definitionFromSignature(signature, kernelId);
    return QStringLiteral(
               "#include <cstddef>\n\n"
               "// User-defined kernel scaffold generated by IRONSmith.\n"
               "%1\n"
               "{\n"
               "    // TODO: implement kernel logic.\n"
               "}\n")
        .arg(definition);
}

} // namespace

KernelRegistryService::KernelRegistryService(QObject* parent)
    : QObject(parent)
    , m_builtInRoot(detectBuiltInRoot())
    , m_globalUserRoot(detectGlobalUserRoot())
{
}

const KernelAsset* KernelRegistryService::kernelById(const QString& kernelId) const
{
    return findKernelById(m_kernels, kernelId);
}

void KernelRegistryService::setBuiltInRoot(const QString& rootPath)
{
    const QString cleaned = cleanPath(rootPath);
    if (m_builtInRoot == cleaned)
        return;

    m_builtInRoot = cleaned;
    emit rootsChanged();
}

void KernelRegistryService::setGlobalUserRoot(const QString& rootPath)
{
    const QString cleaned = cleanPath(rootPath);
    if (m_globalUserRoot == cleaned)
        return;

    m_globalUserRoot = cleaned;
    emit rootsChanged();
}

void KernelRegistryService::setWorkspaceRoot(const QString& workspaceRoot)
{
    const QString cleanedWorkspaceRoot = cleanPath(workspaceRoot);
    const QString cleanedWorkspaceKernelRoot = workspaceKernelRootForWorkspace(cleanedWorkspaceRoot);

    if (m_workspaceRoot == cleanedWorkspaceRoot
        && m_workspaceUserRoot == cleanedWorkspaceKernelRoot) {
        return;
    }

    m_workspaceRoot = cleanedWorkspaceRoot;
    m_workspaceUserRoot = cleanedWorkspaceKernelRoot;
    emit rootsChanged();
}

Utils::Result KernelRegistryService::reload()
{
    KernelCatalogScanRequest request;
    request.builtInRoot = m_builtInRoot;
    request.globalRoot = m_globalUserRoot;
    request.workspaceRoot = m_workspaceUserRoot;

    QVector<KernelAsset> scannedKernels;
    QStringList warnings;
    const Utils::Result scanResult = scanKernelCatalog(request, scannedKernels, &warnings);
    if (!scanResult)
        return scanResult;

    m_kernels = std::move(scannedKernels);

    const bool warningsChanged = (m_warnings != warnings);
    m_warnings = warnings;

    emit kernelsChanged();
    if (warningsChanged)
        emit warningsUpdated(m_warnings);

    if (!m_warnings.isEmpty()) {
        for (const QString& warning : m_warnings)
            qCWarning(aiekernelregistrylog).noquote() << warning;
    }

    return Utils::Result::success();
}

Utils::Result KernelRegistryService::copyKernelToScope(const QString& kernelId,
                                                       KernelSourceScope scope,
                                                       KernelAsset* outCopiedKernel)
{
    if (scope == KernelSourceScope::BuiltIn) {
        return Utils::Result::failure(QStringLiteral("Cannot copy into built-in kernel scope."));
    }

    const KernelAsset* source = kernelById(kernelId);
    if (!source)
        return Utils::Result::failure(QStringLiteral("Kernel not found: %1").arg(kernelId));

    if (!QFileInfo::exists(source->directoryPath) || !QFileInfo(source->directoryPath).isDir()) {
        return Utils::Result::failure(QStringLiteral("Kernel source directory does not exist: %1")
                                          .arg(source->directoryPath));
    }

    const QString targetRoot = rootForScope(scope);
    if (targetRoot.isEmpty())
        return Utils::Result::failure(QStringLiteral("Target kernel root is not available."));

    const Utils::Result ensureRoot = ensureRootDirectory(targetRoot);
    if (!ensureRoot)
        return ensureRoot;

    const QDir targetDir(targetRoot);
    const QString preferredFolder = makeCopyFolderName(source->id);
    const QString uniqueFolder = Utils::FileSystemUtils::uniqueChildName(targetDir, preferredFolder, QString());
    if (uniqueFolder.isEmpty()) {
        return Utils::Result::failure(QStringLiteral("Unable to allocate target folder for kernel copy."));
    }

    const QString destination = Utils::PathUtils::normalizePath(targetDir.filePath(uniqueFolder));
    const Utils::Result copyResult = copyDirectoryRecursively(source->directoryPath, destination);
    if (!copyResult)
        return copyResult;

    const Utils::Result reloadResult = reload();
    if (!reloadResult)
        return reloadResult;

    if (outCopiedKernel) {
        const QString copiedId = source->id;
        const KernelAsset* copied = kernelById(copiedId);
        if (copied)
            *outCopiedKernel = *copied;
    }

    return Utils::Result::success();
}

Utils::Result KernelRegistryService::createKernelInScope(const KernelCreateRequest& request,
                                                         KernelSourceScope scope,
                                                         KernelAsset* outCreatedKernel)
{
    if (scope == KernelSourceScope::BuiltIn) {
        return Utils::Result::failure(QStringLiteral("Cannot create kernels in built-in scope."));
    }

    const QString kernelId = makeKernelIdentifier(request.id);
    if (kernelId.isEmpty())
        return Utils::Result::failure(QStringLiteral("Kernel id is empty or invalid."));

    const QString targetRoot = rootForScope(scope);
    if (targetRoot.isEmpty())
        return Utils::Result::failure(QStringLiteral("Target kernel root is not available."));

    const Utils::Result ensureRoot = ensureRootDirectory(targetRoot);
    if (!ensureRoot)
        return ensureRoot;

    QDir rootDir(targetRoot);
    const QString preferredFolder = makeCopyFolderName(kernelId);
    const QString folderName = Utils::FileSystemUtils::uniqueChildName(rootDir, preferredFolder, QString());
    if (folderName.isEmpty())
        return Utils::Result::failure(QStringLiteral("Failed to allocate folder for new kernel."));

    const QString kernelDirPath = Utils::PathUtils::normalizePath(rootDir.filePath(folderName));
    if (!rootDir.mkpath(folderName)) {
        return Utils::Result::failure(QStringLiteral("Failed to create kernel directory: %1")
                                          .arg(kernelDirPath));
    }

    QString sourceStem = Utils::PathUtils::sanitizeFileName(kernelId);
    sourceStem.replace(' ', '_');
    if (sourceStem.isEmpty())
        sourceStem = QStringLiteral("kernel");

    const QString entryFile = Utils::PathUtils::ensureExtension(sourceStem, QStringLiteral("cpp"));
    const QString entryFilePath = Utils::PathUtils::normalizePath(QDir(kernelDirPath).filePath(entryFile));

    QFile sourceFile(entryFilePath);
    if (!sourceFile.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        return Utils::Result::failure(QStringLiteral("Failed to create kernel source: %1")
                                          .arg(entryFilePath));
    }

    const QString signature = normalizedSignature(request.signature, kernelId);
    const QByteArray sourceBytes = createSourceTemplate(signature, kernelId).toUtf8();
    if (sourceFile.write(sourceBytes) != sourceBytes.size()) {
        return Utils::Result::failure(QStringLiteral("Failed to write kernel source: %1")
                                          .arg(entryFilePath));
    }
    sourceFile.close();

    QJsonObject metadata;
    metadata.insert(QStringLiteral("id"), kernelId);

    QString displayName = request.name.trimmed();
    if (displayName.isEmpty())
        displayName = defaultKernelName(kernelId);
    metadata.insert(QStringLiteral("name"), displayName);
    metadata.insert(QStringLiteral("version"), QStringLiteral("0.1.0"));
    metadata.insert(QStringLiteral("language"), QStringLiteral("cpp"));
    metadata.insert(QStringLiteral("signature"), signature);

    QString description = request.description.trimmed();
    if (description.isEmpty()) {
        description = QStringLiteral("User-defined kernel scaffold.");
    }
    metadata.insert(QStringLiteral("description"), description);
    metadata.insert(QStringLiteral("entry"), entryFile);
    metadata.insert(QStringLiteral("files"), QJsonArray{entryFile});

    QJsonArray tagsArray;
    QStringList tags = request.tags;
    if (tags.isEmpty())
        tags.push_back(QStringLiteral("custom"));
    tags.removeDuplicates();
    for (const QString& tag : tags) {
        const QString cleanedTag = tag.trimmed();
        if (!cleanedTag.isEmpty())
            tagsArray.push_back(cleanedTag);
    }
    if (!tagsArray.isEmpty())
        metadata.insert(QStringLiteral("tags"), tagsArray);

    const QString kernelJsonPath = Utils::PathUtils::normalizePath(
        QDir(kernelDirPath).filePath(QStringLiteral("kernel.json")));
    const Utils::Result writeResult = Utils::JsonFileUtils::writeObjectAtomic(kernelJsonPath, metadata);
    if (!writeResult)
        return writeResult;

    const Utils::Result reloadResult = reload();
    if (!reloadResult)
        return reloadResult;

    if (outCreatedKernel) {
        const KernelAsset* created = kernelById(kernelId);
        if (created)
            *outCreatedKernel = *created;
    }

    return Utils::Result::success();
}

QString KernelRegistryService::detectBuiltInRoot()
{
    const QString envRoot = cleanPath(qEnvironmentVariable("IRONSMITH_BUILTIN_KERNELS_DIR"));
    if (!envRoot.isEmpty())
        return envRoot;

#if defined(IRONSMITH_BUILTIN_KERNELS_DIR)
    const QString compiledRoot = cleanPath(QStringLiteral(IRONSMITH_BUILTIN_KERNELS_DIR));
    if (!compiledRoot.isEmpty())
        return compiledRoot;
#endif

    const QString appDir = cleanPath(QCoreApplication::applicationDirPath());
    if (appDir.isEmpty())
        return {};

    return appDataSubDir(appDir, QStringLiteral("../share/ironsmith/kernels"));
}

QString KernelRegistryService::detectGlobalUserRoot()
{
    Utils::EnvironmentConfig cfg;
    cfg.organizationName = QStringLiteral("IRONSmith");
    cfg.applicationName = QStringLiteral("IRONSmith");

    Utils::Environment env(cfg);
    return appDataSubDir(env.paths().globalConfigDir, QStringLiteral("kernels"));
}

QString KernelRegistryService::workspaceKernelRootForWorkspace(const QString& workspaceRoot)
{
    const QString cleanedWorkspace = cleanPath(workspaceRoot);
    if (cleanedWorkspace.isEmpty())
        return {};

    return appDataSubDir(cleanedWorkspace, QStringLiteral(".ironsmith/kernels"));
}

QString KernelRegistryService::cleanPath(const QString& path)
{
    return Utils::PathUtils::normalizePath(path);
}

Utils::Result KernelRegistryService::ensureRootDirectory(const QString& path) const
{
    const QString cleaned = cleanPath(path);
    if (cleaned.isEmpty())
        return Utils::Result::failure(QStringLiteral("Kernel path is empty."));

    QDir dir(cleaned);
    if (dir.exists())
        return Utils::Result::success();

    if (!dir.mkpath(QStringLiteral(".")))
        return Utils::Result::failure(QStringLiteral("Failed to create kernel directory: %1").arg(cleaned));

    return Utils::Result::success();
}

Utils::Result KernelRegistryService::copyDirectoryRecursively(const QString& sourceDir,
                                                              const QString& targetDir) const
{
    const QString cleanedSource = cleanPath(sourceDir);
    const QString cleanedTarget = cleanPath(targetDir);
    if (cleanedSource.isEmpty() || cleanedTarget.isEmpty())
        return Utils::Result::failure(QStringLiteral("Invalid source/target directory for copy."));

    QDir source(cleanedSource);
    if (!source.exists())
        return Utils::Result::failure(QStringLiteral("Kernel source directory not found: %1").arg(cleanedSource));

    QDir target;
    if (!target.mkpath(cleanedTarget)) {
        return Utils::Result::failure(QStringLiteral("Failed to create destination directory: %1")
                                          .arg(cleanedTarget));
    }

    const QFileInfoList entries = source.entryInfoList(QDir::NoDotAndDotDot | QDir::AllEntries,
                                                       QDir::Name | QDir::IgnoreCase);
    for (const QFileInfo& entry : entries) {
        const QString sourcePath = entry.absoluteFilePath();
        const QString targetPath = QDir(cleanedTarget).filePath(entry.fileName());

        if (entry.isDir()) {
            const Utils::Result recursive = copyDirectoryRecursively(sourcePath, targetPath);
            if (!recursive)
                return recursive;
            continue;
        }

        QFile::remove(targetPath);
        if (!QFile::copy(sourcePath, targetPath)) {
            return Utils::Result::failure(QStringLiteral("Failed to copy '%1' -> '%2'.")
                                              .arg(sourcePath, targetPath));
        }
    }

    return Utils::Result::success();
}

QString KernelRegistryService::rootForScope(KernelSourceScope scope) const
{
    switch (scope) {
        case KernelSourceScope::BuiltIn:
            return m_builtInRoot;
        case KernelSourceScope::Global:
            return m_globalUserRoot;
        case KernelSourceScope::Workspace:
            return m_workspaceUserRoot;
    }
    return {};
}

} // namespace Aie::Internal
